Add in updates to ERC7535 + Oracle
Byzantine-Finance/byzantine-contracts pull request #10
Opened 2024-10-07 10:00 UTC by Tranquil-Flow

2024-10-07 11:14 UTC, asanson1404 requested changes

2024-10-07 11:14 UTC, asanson1404 commented on src/vault/ERC7535MultiRewardVault.sol
> +        uint256 ethPrice = oracle.getPrice(address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE), address(0));
do not use address(0) for the ETH / USDC priceFeed

2024-10-07 11:14 UTC, asanson1404 commented on src/vault/ERC7535MultiRewardVault.sol
> +            uint256 ethPrice = oracle.getPrice(address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE), address(0));
Same here... Why do you use address(0)?

2024-10-07 11:14 UTC, asanson1404 commented on src/vault/ERC7535MultiRewardVault.sol
> +            uint256 ethPrice = oracle.getPrice(address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE), address(0));
Same here, change the priceFeed address

2024-10-09 17:10 UTC, asanson1404 requested changes
Just saw your commit, the code is clean well done Evi :)

I just don't understand why the proxy / priceFeed address on the function `oracle.getPrice()` is still `address(0)`?
Also, don't you think it's better to change the prototype of  `oracle.getPrice` to only have an argument, the token address. The priceFeed / proxy of each token could be store in the OracleImplementation contract.

Also, I thought a bit about that priceFeed vulnerability... How could we be sure that the vault creator will use the correct price feed for the correct tokens and won't use a wrong price feed to boost his rewards or break the vault.
Perhaps, oracle-agnostic means to choose OracleImplementation among a set which has already default and immutable price feed?

I think that would be nice to check the Morpho contracts to see how do they handle that Oracle-agnostic feature

Just saw the interface of Morpho here (no price feed specified):
https://github.com/morpho-org/morpho-blue/blob/fcb190b0e0e1355defe56b19781ac573986c3f74/src/interfaces/IOracle.sol

https://docs.morpho.org/morpho/contracts/oracles/
https://docs.morpho.org/morpho/contracts/oracles/chainlink-oracle-adapter
https://docs.morpho.org/morpho/concepts/oracle-agnostic-pricing
https://docs.morpho.org/morpho/concepts/risk-documentation#oracle-risk

2024-10-10 04:05 UTC, Tranquil-Flow commented
`oracle.getPrice(address token, address priceFeed)` still uses address(0) for `priceFeed` as no value is needed in this call. In the OracleImplementation, if token = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE , then it uses the hardcoded ETH-USD price feed. `priceFeed` does nothing in this call.

Removing the 2nd parameter on the `getPrice` function on IOracle is not a bad idea if we are going with this approach of storing the price feeds for specific tokens on the oracle contracts. It does mean that every new reward token to the vault must have it's price feed stored on the oracle implementation the contract is using - either during the function call to add a reward token or it being an immutable stored variable. In return, it means that oracles are less flexible. They would need a stored price feed to correspond to an address - where as if you pass in a price feed an oracle implementation should work for any price feed that oracle supports.

Morpho has price feed's specified as immutable variables for their `MorphoChainlinkOracleV2` contract which implements their `IOracle`. Basically oracle-agnostic just means that any oracle source/contract can be used as long as calling `price` returns the price given a defined collateral and loan token.

2024-10-10 11:38 UTC, merged